version: '3.8'
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
  data-populator:
    build:
      context: .
      dockerfile: Dockerfile-populator
    depends_on:
      - mongodb
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - mongodb